name: build_deploy_aks
on:
  workflow_dispatch:

  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_SECRET }}
          environment: 'AzureUSGovernment'
          enable-AzPSSession: true

      - name: Azure CLI Action
        uses: Azure/cli@v2.1.0
        env:
          REGISTRY: ${{ secrets.registry }}
          REPO_NAME: workflow
          IMAGE_NAME: azure-vote-front
          IMAGE_TAG: ${{ github.sha }}
        with:
          inlineScript: az acr import --name $REGISTRY --source docker.io/library/hello-world:latest --image $REPO_NAME/$IMAGE_NAME:$IMAGE_TAG --force
