name: build_deploy_aks
on:
  workflow_dispatch:

  push:
    paths:
      - "azure-vote/**"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.registry }}
      REPO_NAME: ${{ secrets.repository }}
      IMAGE_NAME: azure-vote-front
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_SECRET }}
          environment: 'AzureUSGovernment'
          enable-AzPSSession: true
          
      - name: Azure CLI Action
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: az acr import --name ${{ secrets.registry }} --source docker.io/library/hello-world:latest --tag ${{REPO_NAME}}/${{IMAGE_NAME}}:${{IMAGE_TAG}} --force
